# Generated by Django 3.1.5 on 2021-01-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=100, null=True, verbose_name='THE TOP LINE ')),
                ('title2', models.CharField(blank=True, max_length=100, null=True, verbose_name='IN THE MIDDLE LINE')),
                ('title3', models.CharField(blank=True, max_length=100, null=True, verbose_name='LOWEST LINE')),
                ('link', models.URLField(blank=True, null=True, verbose_name='WEB SITE')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SELECTED IMAGE')),
            ],
            options={
                'verbose_name_plural': 'SLIDERS',
            },
        ),
    ]
