# Generated by Django 3.1.5 on 2021-01-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SELECTED IMAGE')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='FOR HOME PAGE SELECTED IMAGE')),
            ],
            options={
                'verbose_name_plural': 'AbOuT',
            },
        ),
    ]
