# Generated by Django 3.1.5 on 2021-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text=':2131/5 sokak no:6 Adalet mahallesi bayraklı', max_length=5500, verbose_name='LOCATION')),
                ('countrylocation', models.CharField(blank=True, max_length=5500, null=True)),
                ('phone', models.IntegerField(verbose_name='PHONE NUMBER')),
                ('fax', models.IntegerField(verbose_name='FAX')),
                ('email1', models.EmailField(max_length=5100)),
                ('web', models.URLField(max_length=5100)),
            ],
            options={
                'verbose_name_plural': 'ConTaCt',
            },
        ),
    ]
