# Generated by Django 3.1.5 on 2021-01-13 16:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name_plural': 'AgEnT'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Home name')),
                ('homeName', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('duplex', 'duplex'), ('villa', 'villa'), ('apartment', 'apartment'), ('commercial', 'commercial'), ('building', 'building'), ('realEstate', 'realEstate')], max_length=53, null=True)),
                ('price', models.IntegerField(verbose_name='Home Type')),
                ('price_unit', models.CharField(choices=[('tl', '₺'), ('euro', '€'), ('dollar', '$')], default='tl', max_length=150, verbose_name='PRICE UNITE')),
                ('bathrooms', models.CharField(max_length=150, verbose_name='BATHROOMS')),
                ('bedroom', models.CharField(max_length=150, verbose_name='BEDROOM')),
                ('square', models.IntegerField(verbose_name='SQUARE')),
                ('parking', models.CharField(max_length=150, verbose_name='GARAJE')),
                ('rooms', models.CharField(max_length=150, verbose_name='ROOMS')),
                ('kitchen', models.IntegerField(blank=True, null=True, verbose_name='KITCHEN')),
                ('imgAppearance', models.ImageField(blank=True, null=True, upload_to='', verbose_name='PICTURE APPEARANCE')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='PICTURE1')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='PICTURE2')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='PICTURE3')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='PICTURE4')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='ADDRESS')),
                ('type', models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], default='rent', max_length=150)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Air Conditioning', 'Air Conditioning'), ('Bedding', 'Bedding'), ('Balcony', 'Balcony'), ('Cable TV', 'Cable TV'), ('Internet', 'Internet'), ('Parking', 'Parking'), ('Lift', 'Lift'), ('Pool', 'Pool'), ('Dishwasher', 'Dishwasher'), ('Toaster', 'Toaster')], max_length=87, null=True, verbose_name='AMENITIES')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('inDate', models.DateField(auto_now_add=True, null=True, verbose_name='ENTRY DATE')),
                ('status', models.BooleanField(default=True, verbose_name='to be seen ?')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.agent', verbose_name='AGENT')),
            ],
            options={
                'verbose_name_plural': 'House',
            },
        ),
    ]
