# Generated by Django 3.1.5 on 2021-01-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_auto_20210113_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField()),
                ('Furnished', models.TextField(verbose_name='Fully Furnished')),
                ('Security', models.TextField(verbose_name='Non Stop Security')),
                ('Design', models.TextField(verbose_name='Latest Interior Design')),
                ('Fittings', models.TextField(verbose_name='Luxurious Fittings')),
                ('LivingInside', models.TextField(verbose_name='Living Inside a Nature')),
                ('RoyalTouchPaint', models.TextField(verbose_name='Royal Touch Paint')),
            ],
            options={
                'verbose_name_plural': 'Features Home',
            },
        ),
    ]
