# Generated by Django 3.1.5 on 2021-01-13 17:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_featureshome'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandimg', models.ImageField(upload_to='', verbose_name='BRAND PICTURE')),
                ('brandsName', models.CharField(blank=True, max_length=200, null=True, verbose_name='BRAND NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='title')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='descriptions details')),
                ('summaryOfDescriptions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'SeRvIs',
            },
        ),
    ]
