# Generated by Django 3.1.5 on 2021-01-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_brandsitem_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img2',
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(verbose_name='PRICE'),
        ),
    ]
