# Generated by Django 3.1.5 on 2021-01-17 06:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_agent_discriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newbuildingdesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('descriptions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('descriptions2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('aboutBuilding', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('inDate', models.DateField(auto_now_add=True, null=True, verbose_name='ENTRY DATE')),
                ('status', models.BooleanField(default=True, verbose_name='to be seen ?')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.agent', verbose_name='AGENT')),
            ],
            options={
                'verbose_name_plural': 'New Building Design',
            },
        ),
    ]
