# Generated by Django 3.1.5 on 2021-01-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_newbuildingdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbuildingdesign',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
