# Generated by Django 3.1.5 on 2021-01-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_newbuildingdesign_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newbuildingdesign',
            new_name='Blog',
        ),
    ]
