# Generated by Django 3.1.5 on 2021-01-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_auto_20210117_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='house',
            name='homeName',
        ),
    ]
