# Generated by Django 3.1.5 on 2021-01-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_auto_20210117_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='house',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='house',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='house',
            name='imgAppearance',
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='selected images')),
                ('status', models.BooleanField(default=True, verbose_name='to be seen?')),
                ('cover', models.BooleanField(default=False, verbose_name='cover image?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pictures', to='ui.house')),
            ],
            options={
                'verbose_name_plural': 'Pictures of the Houses',
            },
        ),
    ]
