# Generated by Django 3.1.5 on 2021-01-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0018_auto_20210117_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price_unit',
            field=models.CharField(choices=[('₺', 'tl'), ('€', 'euro'), ('$', 'dollar')], default='tl', max_length=150, verbose_name='PRICE UNITE'),
        ),
    ]
