# Generated by Django 3.1.5 on 2021-01-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0019_auto_20210117_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='homeName',
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='resim seç')),
                ('status', models.BooleanField(default=True, verbose_name='Gosterilsin mi?')),
                ('cover', models.BooleanField(default=False, verbose_name='kapak resim mi?')),
                ('homeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pictures', to='ui.house', verbose_name='resimler')),
            ],
            options={
                'verbose_name_plural': 'Projeye ait resimler',
            },
        ),
    ]
