# Generated by Django 3.1.5 on 2021-01-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0020_auto_20210118_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='house',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='house',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='house',
            name='imgAppearance',
        ),
    ]
