# Generated by Django 3.1.5 on 2021-01-18 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0021_auto_20210118_0634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name_plural': 'Images for House'},
        ),
        migrations.AddField(
            model_name='house',
            name='homeName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.homename', verbose_name='HoMeNaMe'),
        ),
    ]
