# Generated by Django 3.1.5 on 2021-01-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0022_auto_20210118_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='bedroom',
        ),
    ]
