# Generated by Django 3.1.5 on 2021-01-22 14:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0023_remove_house_bedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Air Conditioning', 'AirConditioning'), ('Bedding', 'Bedding'), ('Balcony', 'Balcony'), ('Cable TV', 'CableTV'), ('Internet', 'Internet'), ('Parking', 'Parking'), ('Lift', 'Lift'), ('Pool', 'Pool'), ('Dishwasher', 'Dishwasher'), ('Toaster', 'Toaster')], max_length=87, null=True, verbose_name='AMENITIES'),
        ),
    ]
