# Generated by Django 3.1.5 on 2021-01-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0025_auto_20210124_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='status',
            field=models.BooleanField(default=True, verbose_name='to be seen ??'),
        ),
    ]
