# Generated by Django 3.1.5 on 2021-01-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0027_auto_20210125_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctrlcomment',
            name='homeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.house', verbose_name='House name'),
        ),
    ]
