# Generated by Django 3.1.5 on 2021-01-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0028_auto_20210125_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='to be seen ??')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.house')),
            ],
        ),
        migrations.DeleteModel(
            name='CtrlComment',
        ),
    ]
