# Generated by Django 3.1.5 on 2021-01-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0029_auto_20210126_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='FirstName and LastName'),
        ),
    ]
