# Generated by Django 3.1.5 on 2021-01-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0030_auto_20210127_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(),
        ),
    ]
