# Generated by Django 3.1.5 on 2021-01-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0031_auto_20210127_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.CharField(max_length=50000),
        ),
    ]
