# Generated by Django 3.1.5 on 2021-01-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0033_auto_20210127_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
