# Generated by Django 3.1.5 on 2021-01-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0034_auto_20210127_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='home',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(),
        ),
    ]
