# Generated by Django 3.1.5 on 2021-01-27 12:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0035_auto_20210127_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
