# Generated by Django 3.1.5 on 2021-02-05 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui', '0038_auto_20210129_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='applied_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Rent', 'rent'), ('Sale', 'sale'), ('PartRent', 'partRent')], default='rent', max_length=150),
        ),
    ]
