# Generated by Django 3.1.5 on 2021-02-05 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui', '0039_auto_20210205_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='applied_users',
        ),
        migrations.AddField(
            model_name='house',
            name='applied_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
