# Generated by Django 3.1.5 on 2021-04-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0041_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(help_text='İlanın bağlanacağı hesap', on_delete=django.db.models.deletion.CASCADE, to='ui.accounts', verbose_name='Hesap')),
                ('homes', models.ManyToManyField(related_name='favorited_posts', to='ui.House', verbose_name='Favori İlanlar')),
            ],
        ),
    ]
