# Generated by Django 3.1.5 on 2021-07-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0042_favoritedposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300000009)),
                ('title', models.CharField(max_length=300000009)),
                ('description', models.CharField(max_length=900000009)),
                ('url', models.CharField(max_length=300000009)),
                ('pic', models.URLField(blank=True, null=True)),
                ('date_of_publish', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
