# Generated by Django 3.1.5 on 2021-07-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0044_remove_news_date_of_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_of_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
